stages:
  - runTestnet
  - runMainnet

run-Testnet:
  stage: runTestnet
  script:
    - ./install t r y
  tags:
    - docker

run-Mainnet:
  stage: runMainnet
  script:
    - ./install m r y
  tags:
    - docker