version: '2'

services:
  iotex:
    container_name: iotex-core
    image: iotex/iotex-core:$JRPC_version
    #Uncomment this section and delete the `image:` section if you want to build the iotex-core repository yourself instead pulling from docker hub
    # build: 
    #     context: $JRPC/external/iotex-core
    #     dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
      - 4689:4689
      - 14014:14014 #native port
      - 8545:15014 #web3 port
      - 16014:16014 #wss socket
    volumes:
      - "/data/Mainnet/IoTeX:/var/data"
      - "/var/log/Mainnet/IoTeX:/var/log"
      - "$JRPC/etc/Mainnet/IoTeX/config-override.yaml:/etc/iotex/config.yaml"
      - "$JRPC/etc/Mainnet/IoTeX/genesis-override.yaml:/etc/iotex/genesis.yaml"
    command: iotex-server -config-path=/etc/iotex/config.yaml -genesis-path=/etc/iotex/genesis.yaml -plugin=gateway