version: '2'

services:
  iotex:
    container_name: iotex-core-testnet
    image: iotex/iotex-core:$JRPC_version
    #Uncomment this section and delete the `image:` section if you want to build the iotex-core repository yourself instead pulling from docker hub
    # build: 
    #     context: $JRPC/external/iotex-core
    #     dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 9080:8080
      - 5690:4690
      - 24014:14014 #native port
      - 8645:15014 #web3 port
      - 26014:16014 #wss socket
    volumes:
      - "/data/Testnet:/var/data"
      - "$JRPC/log/Testnet/IoTeX:/var/log"
      - "$JRPC/etc/Testnet/IoTeX/config-override.yaml:/etc/iotex/config.yaml"
      - "$JRPC/etc/Testnet/IoTeX/genesis-override.yaml:/etc/iotex/genesis.yaml"
    command: iotex-server -config-path=/etc/iotex/config.yaml -genesis-path=/etc/iotex/genesis.yaml -plugin=gateway

